remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Russel Ramos - CSE 455 Final Project
url: 'https://rsslramos.github.io/'
baseurl: 'cse455-birds-classification'